POST  http://localhost:4001/tours
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYxMzQ0MiwiZXhwIjoxNzE4NjE3MDQyfQ.3nrxaMcDHD_it952--pYtCqhKqRxq81l4tRR1BuO5Qg
Content-Type: application/json

{
    "Tourname":"Bonefire adventures",
    "Tourimage":"https://cdn.pixabay.com/photo/2020/12/03/08/05/giraffe-5799824_640.jpg",
    "TDestination":"Ambosseli game park",
    "TDescription":"Experience nature at its best",
    "TPrice":"35000"
}

#####

GET http://localhost:4001/tours

####
GET http://localhost:4001/tours/491b239d-5e7a-4d7d-98cd-ed9934d912a4
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYxMzQ0MiwiZXhwIjoxNzE4NjE3MDQyfQ.3nrxaMcDHD_it952--pYtCqhKqRxq81l4tRR1BuO5Qg

####

DELETE  http://localhost:4001/tours/0a9fef36-5bba-46d6-913a-b6ba333d921a
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYxMzQ0MiwiZXhwIjoxNzE4NjE3MDQyfQ.3nrxaMcDHD_it952--pYtCqhKqRxq81l4tRR1BuO5Qg
####

PATCH   http://localhost:4001/tours/491b239d-5e7a-4d7d-98cd-ed9934d912a4
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYxMzQ0MiwiZXhwIjoxNzE4NjE3MDQyfQ.3nrxaMcDHD_it952--pYtCqhKqRxq81l4tRR1BuO5Qg
Content-Type: application/json

{
    "Tourname":"Bonefire adventures",
    "Tourimage":"https://cdn.pixabay.com/photo/2020/12/03/08/05/giraffe-5799824_640.jpg",
    "TDestination":"Maasai Mara",
    "TDescription":"Experience nature at its best",
    "TPrice":"35000"
}

####

 POST  http://localhost:4001/users/login
 Content-Type: application/json

 {
      "EMAIL": "joe@gmail.com",
    "PASSWORD": "Jona@123"
 }

###
 POST  http://localhost:4001/users/register
 Content-Type: application/json

 {
      "NAME": "Jonathan",
    "EMAIL": "joe@gmail.com",
    "PASSWORD": "Jona@123",
    "ROLE":"USER"
 }

#####
POST  http://localhost:4001/hotels
Content-Type: application/json

{
    "Hotelname":"Mara Frontier",
    "Hotelimage":"https://cdn.pixabay.com/photo/2019/05/28/00/15/indoors-4234071_960_720.jpg",
    "Hlocation":"Sekenani Camp",
    "TourId":"491b239d-5e7a-4d7d-98cd-ed9934d912a4"

}
###
GET  http://localhost:4001/hotels
###
GET  http://localhost:4001/hotels/hotel/6d6f4f47-f40f-40e3-8c97-bde4efea2d93
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYzNTAzOSwiZXhwIjoxNzE4NjM4NjM5fQ._ny7AzbTgDydsnCWvM3W4QY-_rfnSpG4J0J9KZDz7QU
###

GET  http://localhost:4001/hotels/tour/491b239d-5e7a-4d7d-98cd-ed9934d912a4
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYzNTAzOSwiZXhwIjoxNzE4NjM4NjM5fQ._ny7AzbTgDydsnCWvM3W4QY-_rfnSpG4J0J9KZDz7QU
###
DELETE http://localhost:4001/hotels/ced279f7-8521-4e4c-b859-4724eea7a8ad
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYzNTAzOSwiZXhwIjoxNzE4NjM4NjM5fQ._ny7AzbTgDydsnCWvM3W4QY-_rfnSpG4J0J9KZDz7QU

####
PATCH http://localhost:4001/hotels/491b239d-5e7a-4d7d-98cd-ed9934d912a4
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTVUIiOiJjOGFjMDQwZS1hMmVhLTRkYmYtOWJmMS04Y2MyYmUxNmNhZjIiLCJVTkFNRSI6IkxpbnRvbiIsImlhdCI6MTcxODYzNTAzOSwiZXhwIjoxNzE4NjM4NjM5fQ._ny7AzbTgDydsnCWvM3W4QY-_rfnSpG4J0J9KZDz7QU
Content-Type: application/json

{
    "Hotelname":"Mara Gates",
    "Hotelimage":"https://cdn.pixabay.com/photo/2019/05/28/00/15/indoors-4234071_960_720.jpg",
    "Hlocation":"Sekenani Camp",
    "TourId":"491b239d-5e7a-4d7d-98cd-ed9934d912a4"

}

####
POST http://localhost:4001/booking
Content-Type: application/json

{
    "userId":"8ede981c-c9d5-45f5-a2b3-1d6108e84112",
    "tourId":"491b239d-5e7a-4d7d-98cd-ed9934d912a4",
    "hotelId":"6d6f4f47-f40f-40e3-8c97-bde4efea2d93",
    "bstartdate":"20/6/2024",
    "benddate":"30/6/2024",
    "bookingdate":"18/6/2024",
    "bstatus":"Booked"
}

###
GET http://localhost:4001/booking/bookings


###
GET  http://localhost:4001/booking/booking/688659de-e567-4ec4-b74f-6a85003b8170

### 
PATCH  http://localhost:4001/booking/6ac482c7-31d6-45a7-a04d-16420820d18a
Content-Type: application/json

{
    "userId":"8ede981c-c9d5-45f5-a2b3-1d6108e84112",
    "tourId":"491b239d-5e7a-4d7d-98cd-ed9934d912a4",
    "hotelId":"6d6f4f47-f40f-40e3-8c97-bde4efea2d93",
    "bstartdate":"20/6/2024",
    "benddate":"25/6/2024",
    "bookingdate":"1/6/2024",
    "bstatus":"Booked"
}

###
DELETE http://localhost:4001/booking/a2a21e26-8d1d-4a1b-b82e-53f192d0b98e