USE TOUR_MANAGEMENT;
GO 
CREATE OR ALTER PROCEDURE addTour(@ID VARCHAR(255),
@NAME VARCHAR(255),
@IMAGE VARCHAR(255),
@DESTINATION VARCHAR(255),
@DESCRIPTION VARCHAR(255),
@PRICE VARCHAR(255))
AS
BEGIN
INSERT INTO Tours(Id, Tourname, Tourimage, TDescription,TDestination,TPrice) VALUES(@ID,@NAME,@IMAGE,@DESTINATION,@DESCRIPTION,@PRICE)
END