USE TOUR_MANAGEMENT;
GO
CREATE OR ALTER PROCEDURE updateTour(@ID VARCHAR(255),
@NAME VARCHAR(255),
@IMAGE VARCHAR(255),
@DESCRIPTION VARCHAR(255),
@DESTINATION VARCHAR(255),
@PRICE VARCHAR(255))
AS
BEGIN
UPDATE Tours SET 
Tourname=@NAME,
Tourimage=@IMAGE,
TDescription=@DESCRIPTION,
TDestination=@DESTINATION,
TPrice=@PRICE
WHERE Id=@ID
END