USE TOUR_MANAGEMENT;
GO
CREATE OR ALTER PROCEDURE updateHotel(@ID VARCHAR(255),@NAME VARCHAR(255), @IMAGE VARCHAR(255), @LOCATION VARCHAR(255), @TOURID VARCHAR)
AS
BEGIN
UPDATE Hotels SET ID =@ID, Hotelname=@NAME, Hotelimage=@IMAGE, Hlocation=@LOCATION, TourId=@TOURID WHERE ID =@ID
END;