USE TOUR_MANAGEMENT;
GO 
CREATE OR ALTER PROCEDURE addBooking(@ID VARCHAR(255),
@TOURID VARCHAR (255),
@HOTELID VARCHAR (255),
@USERID VARCHAR(255),
@BSTART VARCHAR(255),
@BEND VARCHAR(255),
@BDATE VARCHAR (255),
@BSTATUS VARCHAR(255)
)
AS
 BEGIN
 INSERT INTO Bookings(Id,userId,tourId,hotelId,bstartdate,benddate,bookingdate,bstatus)
 VALUES(@ID,@USERID,@TOURID,@HOTELID,@BSTART,@BEND,@BDATE,@BSTATUS)
 END
