USE TOUR_MANAGEMENT;
GO
CREATE OR ALTER PROCEDURE updateBooking(@ID VARCHAR(255),
@TOURID VARCHAR(255),
@HOTELID VARCHAR(255),
@USERID VARCHAR(255),
@BSTART VARCHAR (255),
@BEND VARCHAR (255),
@BDATE VARCHAR (255),
@BSTATUS VARCHAR(255)
--@BEMAILSENT VARCHAR (255)
)
AS
BEGIN
UPDATE Bookings SET
Id = @ID,
userId = @USERID,
tourId =@TOURID,
hotelId =@HOTELID,
bstartdate =@BSTART,
benddate =@BEND,
bookingdate =@BDATE,
bstatus =@BSTATUS
--isEmailSent =@BEMAILSENT
WHERE Id = @ID;
END