USE TOUR_MANAGEMENT;
CREATE TABLE Bookings(
    Id VARCHAR (255) PRIMARY KEY NOT NULL,
    userId VARCHAR(255),
    bstartdate VARCHAR (255) NOT NULL,
    benddate VARCHAR (255) NOT NULL,
    bookingdate VARCHAR (255) NOT NULL,
    bstatus VARCHAR (255) ,
    isEmailSent INT DEFAULT 0,
    isDeleted INT DEFAULT 0,
    --userId VARCHAR(255)  FOREIGN KEY REFERENCES Users(ID) NOT NULL,
    tourId VARCHAR(255) FOREIGN KEY REFERENCES Tours(Id) NOT NULL,
    hotelId VARCHAR(255)  FOREIGN KEY REFERENCES Hotels(ID) NOT NULL
)

