USE TOUR_MANAGEMENT;
CREATE TABLE Hotels(ID VARCHAR(255) NOT NULL PRIMARY KEY,
Hotelname VARCHAR(255) NOT NULL,
Hotelimage VARCHAR(255) NOT NULL,
Hlocation VARCHAR(255) NOT NULL,
isDeleted INT DEFAULT 0,
TourId VARCHAR (255) FOREIGN KEY REFERENCES Tours (Id) NOT NULL,

)