--CREATE DATABASE TOUR_MANAGEMENT;
USE TOUR_MANAGEMENT;



CREATE TABLE Tours(Id VARCHAR(255) PRIMARY KEY,
Tourname VARCHAR(255) NOT NULL,
Tourimage VARCHAR(255) NOT NULL, 
TDestination VARCHAR(255) NOT NULL,
TDescription VARCHAR(255) NOT NULL,
isDeleted INT DEFAULT 0,
TPrice VARCHAR(255) NOT NULL)